### ISSUE TITLE
error [Errno None] Could not connect to proxy 127.0.0.1:61710 [None] 

### ISSUE THREAD

**Issue by Dastresan** [hiddify/Hiddify_Reality_Scanner#10]
بعد از نصب و ایجاد لیست دامنه و همه اینکارا موقع اجرا سمت کلاینت این ارور رو میده؛

error [Errno None] Could not connect to proxy 127.0.0.1:61710 [None]

چطوری این ارور رو حل کنیم؟

**Comment by mahoor13** [comment]
I've got the same error with random port numbers for each domain!

**Comment by hiddify-com** [comment]
کد را درست اجرا کردید؟
همه چی درست دانلود شده و اولش مشخصات کانفیگ را درست مینویسه؟

**Comment by hossein404** [comment]
سلام این ارور رو میده هنگام اسکن 
{
    "server_address": ایپی",
    "server_port": 11443,
    "short_id": "",
    "public_key": "",
    "uuid": "hiddify",
    "origsni": "",
    "type": "tcp",
    "serviceName": "",
    "mode": ""
}
toya.com [Errno None] Could not connect to proxy 127.0.0.1:56878 [None]
toya.com                :None
 [Errno None] Could not connect to proxy 127.0.0.1:56881 [None]
                :None
zara.com [Errno None] Could not connect to proxy 127.0.0.1:56889 [None]
google.com [Errno None] Could not connect to proxy 127.0.0.1:56890 [None]
yahoo.com [Errno None] Could not connect to proxy 127.0.0.1:56884 [None]
zara.com                :None
google.com              :None
yahoo.com               :None
Finished=============== Sorting results ===============
Nothing found! :(

'security' is not recognized as an internal or external command,
operable program or batch file.
'pbk' is not recognized as an internal or external command,
operable program or batch file.
'sid' is not recognized as an internal or external command,
operable program or batch file.
'sni' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
'flow' is not recognized as an internal or external command,
operable program or batch file.
'encryption' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mahoor13** [comment]
I found the bug! The reality link should be quoted because it contains some ampersand (&) character. Please note this in the README file.

**Comment by hiddify-com** [comment]
الان خطا میدیم اگه این حالت پیش بیاد
