### ISSUE TITLE
اگه تو ویندوز به مشکل خوردین لینک کانفیگ رو تو "" بگذارید

### ISSUE THREAD

**Issue by saeidsm** [hiddify/Hiddify_Reality_Scanner#11]
دسستون درد نکنه. فقط این نکته رو بگم که موقع اجرا روی ویندوز باید
hiddify_reality_scanner "vless_link"
لینک رو داخل "" بگذارین. حداقل برای من اینطوری کار کرد.
سپاس

**Comment by hiddify-com** [comment]
باید حتما اینجوری باشه وگرنه کار نمیکنه
